# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_commands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_commands.proto',
  package='robot_commands',
  serialized_pb='\n\x14robot_commands.proto\x12\x0erobot_commands\"!\n\rrobot_command\x12\x10\n\x08robot_id\x18\x01 \x02(\t')




_ROBOT_COMMAND = _descriptor.Descriptor(
  name='robot_command',
  full_name='robot_commands.robot_command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='robot_commands.robot_command.robot_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['robot_command'] = _ROBOT_COMMAND

class robot_command(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROBOT_COMMAND

  # @@protoc_insertion_point(class_scope:robot_commands.robot_command)


# @@protoc_insertion_point(module_scope)
