# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test_pkg',
  serialized_pb='\n\ntest.proto\x12\x08test_pkg\"\x18\n\x08test_msg\x12\x0c\n\x04name\x18\x01 \x02(\t')




_TEST_MSG = _descriptor.Descriptor(
  name='test_msg',
  full_name='test_pkg.test_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test_pkg.test_msg.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['test_msg'] = _TEST_MSG

class test_msg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEST_MSG

  # @@protoc_insertion_point(class_scope:test_pkg.test_msg)


# @@protoc_insertion_point(module_scope)
